#!/usr/bin/env python

import sys

# grid of Matrix A
matrix_a_rows = 2
matrix_a_cols = 2

# grid of Matrix B
matrix_b_rows = 2
matrix_b_cols = 2

row_index = 0
for line in sys.stdin:
    elements = map(int, line.split())

    # If processing matrix A (first matrix_a_rows lines)
    if row_index < matrix_a_rows:
        for j in range(len(elements)):
            for k in range(matrix_b_cols):
                print(f"{row_index}\t{j}\t{k}\t{elements[j]}")
    # If processing matrix B (remaining lines)
    else:
        for k in range(len(elements)):
            for i in range(matrix_a_rows):
                print(f"{k}\t{i}\t{row_index - matrix_a_rows}\t{elements[k]}")
    
    row_index += 1
