#!/usr/bin/env python

import sys

# grid of Matrix A
matrix_a_rows = 2
matrix_a_cols = 2

# grid of Matrix B
matrix_b_rows = 2
matrix_b_cols = 2

# Initialize result matrix
result_matrix = []

for row in range(matrix_a_rows):
    result_row = []
    for col in range(matrix_b_cols):
        sum_product = 0
        for element in range(matrix_a_cols):
            product = 1
            for num in range(2):
                line = sys.stdin.readline()
                value = map(int, line.split('\t'))[-1]
                product *= value
            sum_product += product
        result_row.append(sum_product)
    result_matrix.append(result_row)

# Print result matrix
print('\n'.join([str(row) for row in result_matrix]))
