#!/usr/bin/env python

import sys

current_key = None
current_value = 0
key = None

for line in sys.stdin:
    if line.strip():  # Ignore empty lines
        values = line.split('\t')
        
        if len(values) != 4:
            continue  # Skip improperly formatted lines
        
        key = tuple(map(int, values[:-1]))
        value = int(values[-1])
        
        if key == current_key:
            current_value += value
        else:
            if current_key:
                print("{0}\t{1}\t{2}\t{3}".format(current_key[0], current_key[1], current_key[2], current_value))
            current_value = value
            current_key = key

# Don't forget to output the last accumulated result
if current_key:
    print("{0}\t{1}\t{2}\t{3}".format(current_key[0], current_key[1], current_key[2], current_value))
